name: skripsi2
description: "Aplikasi Koperasi PT.Rutan"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  file_picker: ^6.1.1
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.7.0
  http: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^8.2.0
  url_launcher: ^6.1.14
  
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  test: any
    
flutter:
  uses-material-design: true
